name: Tests with Dagger (self-hosted)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dagger-ci:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run tests with Dagger
        run: go run main.go
