name: Tests with Dagger (self-hosted)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dagger-ci:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dagger
        run: curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=v0.18.10 BIN_DIR=/usr/local/bin sh


      - name: Run tests with Dagger
        run: go run main.go
