name: Lint with Dagger (self-hosted)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dagger-lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dagger CLI
        run: |
          brew install dagger/tap/dagger
          dagger engine install

      - name: Run lint with Dagger
        run: go run main.go
